# Site settings
title: Felix Höhne | Portfolio
email: hoehnefelix@googlemail.com
url: https://felixhoehne.de
description: "Portfolio Felix Höhne"
meta_author: Hoehne Felix
keywords: "web developer, portfolio"
<<<<<<< HEAD
skills: "Starting Web Developer. I did the Ironhack Bootcamp in Berlin. Self-learner with skills in Javascript, MongoDB, Express, Node.js, React, ES6, HTML, CSS. Through differen positions as  E-Commerce Shop-Manager with I got Product Management experience."
=======
skills: "Starting Web Developer. I did the Ironhack Bootcamp in Berlin. Self-learner with skills in Javascript, MongoDB, Express, Node.js, React, ES6, HTML, CSS."
>>>>>>> 0ad16c2d052d79f88416e163a3d88cd53ecde9a8
baseurl: ""

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Felix Höhne
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/watnFoehn
  - title: linkedin
    url: https://www.linkedin.com/in/felix-hoehne/

# Postal address (add as many lines as necessary)
address:
  - line: Berlin

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
